version: '3.0'

networks:
  backend:
    driver: bridge

services:
  database:
    container_name: "ai-segments-agent2"
    image: "postgres:15.3-alpine"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: project1_db
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend